version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418420578.dkr.ecr.us-east-1.amazonaws.com
      - echo wasi55555 | docker login --username wasiabdullah111 --password-stdin

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t pyimages:latest .
      - docker tag pyimages:latest 905418420578.dkr.ecr.us-east-1.amazonaws.com/pyimages:latest      

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 905418420578.dkr.ecr.us-east-1.amazonaws.com/pyimages:latest

artifacts:
  files:
    - '**/*'
  discard-paths: yes
  name: BuildArtif  # This name should match what is expected in your pipeline configuration
